version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./server:/var/www/html/server
      - ./nginx.conf:/etc/nginx/sites-available/default
    environment:
      - DB_HOST=localhost
      - DB_NAME=kuro_app
      - DB_USER=root
      - DB_PASS=
    restart: unless-stopped
